name: Build and Dockerize

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Run test with maven
      run: mvn verify
      
    - name: Dockerize and Push
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      run: |
       VERSION='uuidgen'
       docker login --username $DOCKERHUB_USERNAME  --password $DOCKERHUB_PASSWORD
       docker build -t pjamir/usermanagement:$VERSION .
       docker push pjamir/usermanagement:$VERSION
         
        
      
    
    
    
   
